const onlyAdmin : string = "Only admin";
const accessDenied : string = "Access denied";
const tooEarly : string = "Too early to release payment";
const alreadyExists : string = "Escrow already exists";
const doesntExist : string = "Escrow not found";
const notRightAmount : string = "The amount sent doesn't correspond to the price";
const badAddress : string = "Bad address";
const alreadyFinished : string = "Escrow already finished";
const already_canceled : string = "Cancel already requested"