name: Run Python Tests
on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: escrow/main
    steps:
      - uses: actions/checkout@v2
      - name: Install Python 3
        uses: snok/install-poetry@v1.1.1
        with:
          python-version: '3.7.x'
      - name: Install dependencies
        run: |
          sudo apt-get update -q
          sudo apt install libsodium-dev libsecp256k1-dev libgmp-dev -y
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run tests
        run: python3 test_escrow.py
