name: Run Python Tests
on:
  push:
    branches:
      - master
      - dev
      - Lucas
  pull_request:
    branches:
      - dev
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build docker image
        run: |
          docker build . -t escrow
      - name: Run tests
        run: |
          docker run escrow:latest
